image: node:14.15.0

stages:
  - build
  - deploy

.assume_role: &assume_role
    - >
      STS=($(aws sts assume-role-with-web-identity
      --role-arn ${ROLE_ARN}
      --role-session-name "GitLabRunner-${CI_PROJECT_ID}-${CI_PIPELINE_ID}"
      --web-identity-token $ID_TOKEN
      --duration-seconds 3600
      --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]'
      --output text))
    - export AWS_ACCESS_KEY_ID="${STS[0]}"
    - export AWS_SECRET_ACCESS_KEY="${STS[1]}"
    - export AWS_SESSION_TOKEN="${STS[2]}"

build_Gatsby:
  stage: build
  tags:
    - its-web
  script:
    - pwd
    - npm install
    - npm install -g gatsby-cli@4.24.0
    - node -v
    - npm -v
    - yarn -v
    - gatsby -v
    - gatsby build
  artifacts:
    paths:
    - public

deploy_staging_s3:
  stage: deploy
  image:
    name: amazon/aws-cli:latest
    entrypoint: 
      - '/public'
  id_tokens:
      ID_TOKEN:
        aud: indispensable_dev
  script:
    - *assume_role
    - aws s3 sync build/ s3://$S3_BUCKET
